version: "3.7"

services:
  cockroachdb:
    image: cockroachdb/cockroach:v21.2.7
    command:
      - start-single-node
      - --insecure
      - --listen-addr=0.0.0.0:23257
    ports:
      - 23257:23257

  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    ports:
      - "4160:4160"
      - "4161:4161"
    command: [
      "/nsqlookupd"
    ]

  nsqd:
    image: nsqio/nsq:v1.2.1
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookupd
    command: [
      "/nsqd",
      "--broadcast-address",
      "localhost",
      "--lookupd-tcp-address=nsqlookupd:4160"
    ]

  nsqadmin:
    image: nsqio/nsq:v1.2.1
    ports:
      - "4271:4171"
    depends_on:
      - nsqd
      - nsqlookupd
    command: [
      "/nsqadmin",
      "--lookupd-http-address=nsqlookupd:4161"
    ]
